services:
  windows:
    image: dockurr/windows
    container_name: windows
    restart: always # Thêm dòng này
    environment:
      VERSION: "10l"
      USERNAME: "SpaceX"
      PASSWORD: "123456"
      RAM_SIZE: "8G"
      CPU_CORES: "3"
      DISK_SIZE: "100G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
